services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: david
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: DB_ejercicio
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    ports:
      - "5432:5432"

volumes:
  postgres_data: